name: CI

on:
  issue_comment:
    types: [created]
  issues:
    types: [created]
  

jobs:
  sentiment:

    runs-on: ubuntu-latest

    steps:
    - uses: mattdsteele/salty-issue-detector@releases
      name: Salty Issues
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
